version: '3.9'
services:
    postgres:
      image: postgres:latest
      restart: always
      ports:
        - 5432:5432
      hostname: localhost
      environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: user
        POSTGRESS_DB: crawler
      volumes:
        - ./dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
    name: ./dbdata